name: Run Python script and append output to file

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
     inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:                    # Global permissions configuration starts here
  contents: write                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests
jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python tefas.py >> daily_result.txt

    - name: Set up Git
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.email $GH_EMAIL
        git config --global user.name $GH_USERNAME
        git remote set-url origin https://kursadaltan:${{ secrets.GH_TOKEN }}@github.com/kursadaltan/tefas_fon_rsi_takip
        git add daily_result.txt
        git commit --allow-empty -m "Update Daily Result file with script output"
        git push origin main
