name: Run Python script and append output to file

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
     inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python tefas.py >> daily_result.txt

    - name : Update Document
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run : |
        git clone  https://kursadaltan:$GH_TOKEN@github.com/kursadaltan/tefas_fon_rsi_takip -b main
        cd tefas_fon_rsi_takip
        git config --global user.email "$GH_EMAIL"
        git config --global user.name "$GH_USERNAME"
        git add .
        git commit --allow-empty -m "add daily report"
        git push origin main   
